---
title: 'Assignment #4: Sensitivity Analysis'
author: "Hannah Garcia-Wickstrum"
date: "4/21/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sensitivity)
library(tidyverse)
library(pse)
library(tinytex)
```

### Latin Hypercube Sensitivity Analysis 
```{r, message=FALSE, warning=FALSE}
# read in function & data
source('compute_almond_yield.R')
clim =read.table("clim.txt")

# Test run function
test_func <- compute_almond_yield(clim = clim)

# precipitation parameter factors
factors = c("Pcoeff1", "Pcoeff2")

# Decide How many parameter sets to run
nsets=100

# Assumptions: precipitation has uniform distribution
q = c("qunif", "qunif")
q.arg = list(list(min=-0.084,max=-0.056), list(min=0.00344, max=0.00516))

# generate samples from LHS
sens_almond = LHS(NULL,factors,nsets,q,q.arg)
sens_pars = get.data(sens_almond)
head(sens_pars)

# Run the model for all of the parameters generated by LHS
res = sens_pars %>% 
  pmap(compute_almond_yield,clim=clim)
head(res)

# turn results in to a dataframe for easy display/analysis
resd = res %>% 
  map_dfr(`[`,c("sdyield","meanyield"))

```

### Scatter plot
```{r, message=FALSE, warning=FALSE}
sens_almond = pse::tell(sens_almond, 
                        t(as.matrix(resd)), 
                        res.names=c("sdyield","meanyield"))

# Analyze parameter sensitivity
pse::plotscatter(sens_almond, col="blue", cex=5)
```

### PRCC plot
```{r, message=FALSE, warning=FALSE}
# prcc plot
pse::plotprcc(sens_almond)
sens_almond$prcc
```

Based on the scatter and PRCC plots, **Pcoeff2** contributes more to paramter uncertainty. 
